spring.application.name=Aluno Online

# Configuração do Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/aluno_online_casa?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=13Lorand
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Pool de Conexões (Hikari)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# Logging SQL (para debug)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# CHAVE
api.security.token.secret=${JWT_SECRET:123456}
